select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, precio, (precio*0.9197) from producto;
select nombre, precio as euro, (precio*0.9197) as dollar from producto;
select upper(nombre), precio from producto;
select lower(nombre), precio from producto;
select nombre,upper( substring(nombre, 1,2 )) from fabricante;
select nombre, round(precio) from producto;
select nombre, floor(precio) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre from fabricante order by nombre;
select nombre from fabricante order by nombre desc;
select nombre, precio from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 3,2;
select nombre, precio from producto order by precio limit 1 ;
select nombre, precio from producto order by precio desc limit 1 ;
select nombre from producto where codigo_fabricante=2;
select p.nombre, p.precio, f.nombre as "fabric name" from producto p join fabricante f on codigo_fabricante=f.codigo;
select p.nombre, p.precio, f.nombre as "fabric name" from producto p join fabricante f on codigo_fabricante=f.codigo order by p.nombre;
select p.codigo as "product code", p.nombre as "product name", f.codigo as "fabric code", f.nombre as "fabric name" from producto p join fabricante f on codigo_fabricante=f.codigo;
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where p.precio=(select min(precio) from producto);
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where p.precio=(select max(precio) from producto);
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where f.nombre="lenovo";
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where f.nombre="crucial" and p.precio>200;
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where f.nombre="asus" or f.nombre="Hewlett-Packard" or f.nombre="seagate";
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where f.nombre in ("asus" ,"Hewlett-Packard" ,"seagate");
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where right(f.nombre, 1)='e';
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where f.nombre like '%w%';
select p.nombre, p.precio, f.nombre as fabrica from producto p join fabricante f on codigo_fabricante=f.codigo where p.precio>=180 order by p.precio desc, p.nombre asc;
select distinct f.codigo, f.nombre from fabricante f join producto p on p.codigo_fabricante=f.codigo;
select f.nombre, p.nombre from fabricante f left join producto p on p.codigo_fabricante=f.codigo;
select f.nombre, p.nombre from fabricante f left join producto p on p.codigo_fabricante=f.codigo where p.nombre is null;
select p.nombre from producto p left join fabricante f on p.codigo_fabricante=f.codigo where f.nombre="lenovo";
select p.nombre, p.precio from producto p where precio=(select max(precio) from producto p join fabricante f on codigo_fabricante=f.codigo  where f.nombre="lenovo");
select p.nombre, p.precio from producto p where precio=(select max(precio) from producto p inner join fabricante f on codigo_fabricante=f.codigo  where f.nombre="lenovo");
select p.nombre, p.precio from producto p where precio=(select min(precio) from producto p inner join fabricante f on codigo_fabricante=f.codigo  where f.nombre="Hewlett-Packard");
select p.nombre, p.precio from producto p where precio>=(select max(precio) from producto p join fabricante f on codigo_fabricante=f.codigo  where f.nombre="lenovo");
select p.nombre, p.precio from producto p where precio>(select avg(precio) from producto p join fabricante f on codigo_fabricante=f.codigo  where f.nombre="asus");
